stroka = input("Введите строку ")
print("Третий символ: ", stroka[2])
print("Предпоследний сивол: ", stroka[-2])
print("Первые пять: ", stroka[:5])
print("Кроме последних двух: ", stroka[:(len(stroka)-2)])
print("С четными индексами: ", stroka[::2])
print("С нечетными индексами: ", stroka[1::2])
print("В обратном порядке: ", stroka[::-1])
print("Через один в обратном: ", stroka[-1::-2])
print("Длина строки =", len(stroka))